/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 5276c5247fd21283909459b5337cde08)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	VNPT_EKYC_TOKEN_ID: string;
	VNPT_EKYC_TOKEN_KEY: string;
	VNPT_EKYC_ACCESS_TOKEN: string;
	VNPT_BOT_TOKEN_ID: string;
	VNPT_BOT_TOKEN_KEY: string;
	VNPT_BOT_ACCESS_TOKEN: string;
	SMARTBOT_BOT_ID: string;
	VNPT_VISION_TOKEN_ID: string;
	VNPT_VISION_TOKEN_KEY: string;
	VNPT_VISION_ACCESS_TOKEN: string;
	VNPT_VOICE_BASE_URL: string;
	VNPT_VOICE_TOKEN_ID: string;
	VNPT_VOICE_TOKEN_KEY: string;
	VNPT_VOICE_ACCESS_TOKEN: string;
	VNPT_READER_TOKEN_ID: string;
	VNPT_READER_TOKEN_KEY: string;
	VNPT_READER_ACCESS_TOKEN: string;
	VNPT_VNFACE_CHANNEL: string;
	VNPT_VNFACE_ACCESS_TOKEN: string;
	ADMIN_EMAIL: string;
	ADMIN_PASSWORD: string;
	TEACHER_EMAIL: string;
	TEACHER_PASSWORD: string;
	AUTH_SECRET: string;
	WORKER_SELF_REFERENCE: Fetcher /* phylab-v2 */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VNPT_EKYC_TOKEN_ID" | "VNPT_EKYC_TOKEN_KEY" | "VNPT_EKYC_ACCESS_TOKEN" | "VNPT_BOT_TOKEN_ID" | "VNPT_BOT_TOKEN_KEY" | "VNPT_BOT_ACCESS_TOKEN" | "SMARTBOT_BOT_ID" | "VNPT_VISION_TOKEN_ID" | "VNPT_VISION_TOKEN_KEY" | "VNPT_VISION_ACCESS_TOKEN" | "VNPT_VOICE_BASE_URL" | "VNPT_VOICE_TOKEN_ID" | "VNPT_VOICE_TOKEN_KEY" | "VNPT_VOICE_ACCESS_TOKEN" | "VNPT_READER_TOKEN_ID" | "VNPT_READER_TOKEN_KEY" | "VNPT_READER_ACCESS_TOKEN" | "VNPT_VNFACE_CHANNEL" | "VNPT_VNFACE_ACCESS_TOKEN" | "ADMIN_EMAIL" | "ADMIN_PASSWORD" | "TEACHER_EMAIL" | "TEACHER_PASSWORD" | "AUTH_SECRET">> {}
}
