const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='boole-studio-chapter2-v1', TOTAL=LESSONS.reduce((n,l)=>n+l.tasks.length,0);
let saved={},storageOk=true;
try{saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(!saved||typeof saved!=='object')saved={};}catch{storageOk=false;}
const validIds=new Set(LESSONS.flatMap(l=>l.tasks.map(t=>t.id)));
const done=new Set(Array.isArray(saved.done)?saved.done.filter(x=>validIds.has(x)):[]);
const S={lesson:Number.isInteger(saved.lesson)&&saved.lesson>=-1&&saved.lesson<LESSONS.length?saved.lesson:-1,task:0,step:0,view:'map',frame:0,pos:false,selected:[],speed:1,playing:false,group:-1,expanded:'Bìa Karnaugh',hint:0};
if(S.lesson>=0){S.task=Number.isInteger(saved.task)&&saved.task>=0&&saved.task<LESSONS[S.lesson].tasks.length?saved.task:0;S.expanded=LESSONS[S.lesson].category;}
const categoryIcons={'Đại số':'ƒ','Bảng chân trị':'01','Giản đồ xung':'⌁','Bìa Karnaugh':'▦','Mạch logic':'⊕','NAND / NOR':'⊼'};
const stepNames=['Đọc đề','Quan sát','Dạng chuẩn','Rút gọn','Lời giải','Tự kiểm tra'];
const introNames=['Ý tưởng','Mã Gray','Gom nhóm','Qua mép','Ô X','Thử sức'];
const introSteps=[
['Bìa K là bảng chân trị được sắp lại.','Mỗi ô ứng với đúng một bộ đầu vào. Số nhỏ là chỉ số minterm; số lớn là giá trị F. Bản đồ đang biểu diễn F(A,B,C,D) có 16 tổ hợp.','Bấm một ô: bạn sẽ thấy nó tương ứng với bộ ABCD nào.','Mục tiêu: gom các ô 1 để tìm biểu thức ngắn hơn.'],
['Vì sao 00 → 01 → 11 → 10?','Đây là thứ tự Gray: hai nhãn kề nhau chỉ đổi một bit. Ví dụ 01 → 11 chỉ đổi bit đầu. Nếu viết 00,01,10,11 thì 01 → 10 đổi cả hai bit, không thể khử một biến trực tiếp.','Chọn m0 và m2 ở hai mép: CD=00 và CD=10 chỉ khác C.','00 và 10 cũng kề nhau; bìa K nối vòng ở cả hai chiều.'],
['Một nhóm, một tích ngắn hơn.','Gom 1, 2, 4, 8 hoặc 16 ô thành hình chữ nhật. Trong nhóm, biến đổi giá trị sẽ bị khử; biến giữ nguyên sẽ ở lại. Nhóm 4 ô khử 2 biến.','Chọn m0, m2, m8, m10. A và C thay đổi, B=0 và D=0 giữ nguyên.','Một ô có thể thuộc nhiều nhóm. Cần phủ đủ mọi ô 1; tránh nhóm chứa ô 0.'],
['Bốn góc thật ra ở cạnh nhau.','Hãy tưởng tượng gập mép trái chạm mép phải, mép trên chạm mép dưới. Bốn ô góc là một nhóm 4 hợp lệ, không phải bốn nhóm rời.','Nhóm {0,2,8,10} → !B!D. Không gom chéo tùy ý; các ô phải tạo một khối đầy đủ trên bìa nối vòng.','Cả hai mép được nối. Với 5 biến, hai lớp có các ô cùng vị trí cũng kề nhau.'],
['Ô X giúp nới nhóm, khi có lợi.','X ở đầu ra là don’t-care: có thể chọn 0 hoặc 1. Ví dụ này có các ô 1 tại 1,3,7 và X tại 5. Dùng ô 5 sẽ tạo nhóm 4 thay vì hai nhóm 2.','Chọn {1,3,5,7}. A luôn 0 và D luôn 1 → !AD.','Không cần phủ tất cả X. X ở cột đầu vào của một hàng gộp lại mang nghĩa khác.'],
['Tự đọc một nhóm bốn ô.','Bìa này có nhóm {0,1,4,5}. Hãy chọn cả bốn ô, nhìn biến nào thay đổi, rồi chọn tích tương ứng bên dưới.','AB chạy qua 00,01 nên B đổi. CD chạy qua 00,01 nên D đổi.','SOP gom 1: bit 0 cho biến phủ định. POS gom 0: bit 0 cho biến không phủ định.']
];
function currentLesson(){return LESSONS[S.lesson];}
function currentTask(){return currentLesson()?.tasks[S.task];}
function format(expr){return esc(expr).replace(/!([A-Z][0-9]*)/g,'<span class="over">$1</span>').replace(/\*/g,'·').replace(/\^/g,' ⊕ ').replace(/\+/g,' + ');}
function listIndices(t,value){return t.values.flatMap((v,i)=>v===value?[i]:[]);}
function indexText(t,pos=false){const d=listIndices(t,'X');return (pos?'ΠM':'Σm')+'('+listIndices(t,pos?0:1).join(', ')+')'+(d.length?' ; d('+d.join(', ')+')':'');}
function save(){try{localStorage.setItem(KEY,JSON.stringify({done:[...done],lesson:S.lesson,task:S.task,introDone:!!saved.introDone}));}catch{storageOk=false;}updateProgress();}
function updateProgress(){$('#progressText').textContent=done.size+' / '+TOTAL;$('#progressBar').style.width=(done.size/TOTAL*100)+'%';$('#storageState').textContent=storageOk?'Tự lưu trên trình duyệt này':'Không lưu được · giữ tab này để giữ tiến độ';}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function availableViews(){const t=currentTask();if(!t)return [['map','Bìa K']];return [...(t.proof?[['proof','Biến đổi']]:[]),['truth','Bảng'],['map','Bìa K'],['circuit','Mạch'],...(t.wave?[['wave','Xung']]:[]),...(t.decoder!==undefined?[['decoder','8 ngõ ra']]:[])];}
function chooseView(){const t=currentTask(),l=currentLesson();if(!t)return'map';if(t.proof)return'proof';if(t.decoder!==undefined)return'decoder';if(t.wave)return'wave';if(l.category==='Bìa Karnaugh'||l.category==='NAND / NOR')return'map';if(l.category==='Mạch logic')return'circuit';return'truth';}
function stop(){S.playing=false;clearTimeout(timer);$('#playBtn').textContent='▶';$('#playBtn').setAttribute('aria-label','Chạy animation');}
function selectLesson(index,task=0){stop();S.lesson=index;S.task=task;S.step=0;S.frame=0;S.selected=[];S.pos=currentTask()?.prefer==='pos';S.group=-1;S.hint=0;circuitMode=null;S.view=chooseView();if(index>=0)S.expanded=currentLesson().category;document.body.classList.remove('menu-open');save();render();window.scrollTo({top:0,behavior:'instant'});}
function setStep(step){stop();S.step=Math.max(0,Math.min(5,step));S.selected=[];S.group=-1;S.frame=0;S.hint=0;const t=currentTask();if(S.lesson<0){S.view='map';S.pos=false;}else if(t.proof){S.view='proof';S.frame=Math.min(Math.max(0,S.step-1),t.proof.length-1);}else if(S.step===1)S.view=t.wave?'wave':'truth';else if(S.step===2)S.view='truth';else if(S.step===3)S.view='map';else if(S.step===4)S.view=t.decoder!==undefined?'decoder':t.gate?'circuit':'map';render();}
function renderNav(){
  $('#lessonNav').innerHTML=`<button class="nav-intro ${S.lesson<0?'active':''}" data-lesson="-1"><span class="nav-icon">✦</span> Bắt đầu với bìa K ${saved.introDone?'✓':''}</button><div class="nav-divider">HỌC THEO DẠNG</div>`+Object.keys(categoryIcons).map(cat=>{const list=LESSONS.map((l,i)=>({...l,index:i})).filter(l=>l.category===cat),active=S.expanded===cat;return `<button class="category-button ${active?'active':''}" data-category="${cat}" aria-expanded="${active}"><span class="nav-icon">${categoryIcons[cat]}</span>${cat}<span class="count">${list.length}</span></button>${active?'<div class="category-lessons">'+list.map(l=>`<button class="lesson-link ${l.index===S.lesson?'active':''} ${l.tasks.every(t=>done.has(t.id))?'done':''}" data-lesson="${l.index}" title="${esc(l.title)}"><span class="lesson-number">${l.id.replace('-I',' · I').replace('I-I','II')}</span><span>${l.title}</span></button>`).join('')+'</div>':''}`;}).join('');updateProgress();
}
function render(){
  renderNav();const l=currentLesson(),t=currentTask(),intro=!l;
  $('#crumb').textContent=intro?'Bìa Karnaugh':l.category;
  $('#eyebrow').textContent=intro?'MỘT KHỞI ĐẦU NHẸ NHÀNG':'BÀI '+l.id+' · '+l.category;
  $('#title').textContent=intro?'Bìa K, nhìn là hiểu.':l.title;
  $('#subtitle').textContent=intro?'6 bước ngắn để nhìn ra quy luật, gom nhóm và tự rút gọn một hàm Boole.':l.request;
  $('#lessonBadge').textContent=intro?'NHẬP MÔN':`TR. ${l.page} / BTC2`;
  $('#taskPicker').innerHTML=intro?'':`<div class="task-picker" role="group" aria-label="Chọn câu hoặc hàm">${l.tasks.map((x,i)=>`<button class="task-chip ${i===S.task?'active':''} ${done.has(x.id)?'done':''}" data-task="${i}">${esc(x.name)} ${done.has(x.id)?'✓':''}</button>`).join('')}</div>`;
  $('#stepper').innerHTML=(intro?introNames:stepNames).map((s,i)=>`<button class="step-button ${i===S.step?'active':i<S.step?'past':''}" data-step="${i}" ${i===S.step?'aria-current="step"':''}><b>${String(i+1).padStart(2,'0')}</b>${s}</button>`).join('');
  $('#viewTabs').innerHTML=availableViews().map(([id,title])=>`<button data-view="${id}" class="${S.view===id?'active':''}" aria-pressed="${S.view===id}">${title}</button>`).join('');
  $('#coachMeta').textContent=intro?'Bìa K căn bản':l.id+' / '+t.name;
  $('#stepCount').textContent=(S.step+1)+' / 6';
  $('#prevBtn').disabled=S.step===0;$('#skip1').disabled=S.step>=5;$('#skip2').disabled=S.step>=5;
  $('#nextBtn').innerHTML=S.step===5?(intro?'Khám phá bài tập <span>→</span>':'Mục tiếp theo <span>→</span>'):'Hiểu rồi, tiếp tục <span>→</span>';
  renderCoach();renderVisual();renderBelow();
}
function renderCoach(){
  const l=currentLesson(),t=currentTask();
  if(!l){const [title,text,hint,note]=introSteps[S.step];$('#coachContent').innerHTML=`<h2>${title}</h2><p>${text}</p><div class="key">${hint}</div>${S.step===5?`<p>Kết quả của nhóm {0,1,4,5} là gì?</p><div class="quiz-options">${['!A!C','!B!D','AC'].map((x,i)=>`<button class="quiz-option" data-intro-answer="${i}"><span class="formula">${format(x)}</span></button>`).join('')}</div><div id="feedback" aria-live="polite"></div>`:`<p>${note}</p>`}`;return;}
  if(t.proof&&S.step<5){const idx=Math.min(Math.max(0,S.step-1),t.proof.length-1),p=t.proof[idx];$('#coachContent').innerHTML=`<h2>${S.step===0?'Chứng minh, không chỉ thử số.':p[0]}</h2><p>${S.step===0?l.insight:p[2]}</p><div class="formula-panel formula">${format(S.step===0?t.right:p[1])}</div><div class="key">${S.step===0?'Ta bắt đầu từ vế dễ biến đổi hơn. Bấm ▶ để xem chuỗi biến đổi; bảng bên cạnh cho phép đối chiếu bằng từng tổ hợp đầu vào.':'Đổi sang tab Bảng để kiểm chứng: giá trị hàm không đổi sau phép biến đổi này.'}</div>`;return;}
  const one=listIndices(t,1),zero=listIndices(t,0),dc=listIndices(t,'X'),result=t.prefer==='pos'?t.pos:t.sop;
  if(S.step===0)$('#coachContent').innerHTML=`<h2>Nhìn đúng dữ kiện trước.</h2><p>${l.insight}</p><div class="formula-panel formula">${esc(t.name)} = ${t.expr?format(t.expr):esc(t.given||indexText(t))}</div><div class="key">Thứ tự biến: <b>${t.vars.join(', ')}</b>.<br>Chỉ số i đọc từ trái sang phải, bit trái có trọng số lớn nhất.</div>${t.partial?'<div class="source-note">X của bài này = trạng thái chưa xuất hiện trên hình; không phải thông tin khẳng định đầu ra là don’t-care.</div>':''}`;
  else if(S.step===1)$('#coachContent').innerHTML=`<h2>${t.wave?'Dừng giữa hai cạnh xung.':'Theo dõi từng tổ hợp.'}</h2><p>${t.wave?'Kéo con trỏ thời gian và đọc các bit vào cùng một lúc. Sau đó đổi bộ bit thành chỉ số i. Một trạng thái lặp lại vẫn chỉ là một hàng trong bảng.':'Bấm ▶ để quét các hàng, hoặc bấm một hàng bất kỳ. Mỗi bit đầu vào đổi sẽ làm mạch tính lại ngay.'}</p><div class="key">Có <b>${one.length}</b> hàng 1, <b>${zero.length}</b> hàng 0${dc.length?' và <b>'+dc.length+'</b> hàng X':''}.</div><p>${l.id==='2-7'?'Hàng 1XXX trong đề được khai triển thành các chỉ số 8–15. Mỗi hàng có đầu ra cố định.':l.id==='2-2'?'Với thứ tự CBA: 101 nghĩa là C=1,B=0,A=1, ứng với chỉ số 5.':'Đừng đọc giá trị ngay trên cạnh chuyển mức. Mô hình này xét các mức logic ổn định, chưa xét trễ truyền.'}</p>`;
  else if(S.step===2)$('#coachContent').innerHTML=`<h2>Hàng 1 tạo Σ. Hàng 0 tạo Π.</h2><p>Minterm: bit 0 viết biến phủ định, bit 1 viết biến thường. Maxterm thì ngược lại để tổng đó bằng 0 đúng tại hàng đang xét.</p><div class="formula-panel monosmall">${esc(t.name)} = ${indexText(t)}<br>${esc(t.name)} = ${indexText(t,true)}</div><div class="key">Mỗi tích/tổng trong dạng chuẩn phải chứa đủ ${t.vars.length} biến.${dc.length?' Tập d tách riêng, không gộp vào cả hai danh sách.':''}</div><p>Xem khai triển đầy đủ ở phần “Lời giải để đối chiếu” phía dưới.</p>`;
  else if(S.step===3)$('#coachContent').innerHTML=`<h2>${l.mapOnly?'Đặt đúng vị trí trên bìa K.':'Giữ biến cố định, bỏ biến đổi.'}</h2><p>${l.mapOnly?'Đổi chỉ số sang bit rồi tìm hàng/cột theo mã Gray. Bấm từng ô để đối chiếu chỉ số, bộ bit và đầu ra. Việc gom nhóm là phần luyện thêm.':`Chế độ ${S.pos?'POS gom ô 0':'SOP gom ô 1'}. Chọn vài ô để thử một nhóm. Bấm “Nhóm mẫu” để thấy các nhóm của lời giải lần lượt.`}</p><div class="key">Nhóm hợp lệ có 1,2,4,8,… ô và là một khối đầy đủ. Cho phép nối mép và chồng nhóm; không được chứa ô ${S.pos?'1':'0'}.</div><p>${t.vars.length===5?'Hai bìa A=0 và A=1 có thể ghép các ô cùng vị trí. Chọn đủ các ô ở cả hai lớp để khử A.':dc.length?'Có thể mượn X để nới nhóm. Chỉ các ô xác định cần được phủ hết.':'Tìm nhóm lớn trước; sau đó kiểm tra không còn ô cần phủ bị bỏ sót.'}</p>`;
  else if(S.step===4)$('#coachContent').innerHTML=`<h2>${t.gate?'Từ công thức thành cổng.':'Chốt lời giải và đối chiếu.'}</h2><div class="formula-panel formula">${esc(t.name)} = ${format(result.expr)}</div><p>${t.gate?`Đây là một dạng ${t.prefer==='pos'?'POS':'SOP'} tối giản. Chọn tab Mạch: các dây sáng biểu diễn mức 1. Bạn có thể đổi từng bit đầu vào và xem kết quả.`:'Đây là một biểu thức tối giản hợp lệ. Dạng chuẩn Σ/Π và biểu thức đầy đủ nằm phía dưới; hãy kiểm tra đúng thứ tự biến trước khi ghi đáp án.'}</p><div class="key">${t.gate? t.gate.startsWith('nor')?'NOR(x,x)=!x. Để thực hiện a·b, dùng NOR(!a,!b). Để OR, lấy NOR rồi đảo lại.':'NAND(x,x)=!x. Để thực hiện a+b, dùng NAND(!a,!b). Để AND, lấy NAND rồi đảo lại.':dc.length?'Có thể có nhiều lời giải tương đương trên các hàng xác định nhưng khác nhau ở các ô X. Đều được chấp nhận.':'Thay lần lượt mọi tổ hợp để đối chiếu kết quả. Khác hình thức vẫn có thể là cùng một hàm.'}</div>${t.both?'<p>Trong tab Mạch, chuyển “Theo biểu thức” để xem cấu trúc AND–OR / OR–AND trước khi đổi cổng.</p>':''}`;
  else if(S.step===5){
    $('#coachContent').innerHTML=`<h2>Tới lượt bạn.</h2>${t.proof?`<p>${t.question}</p><div class="quiz-options">${t.options.map((o,i)=>`<button class="quiz-option" data-proof-answer="${i}">${esc(o)}</button>`).join('')}</div>`:`<p>Viết một kết quả cho ${esc(t.name)}. App kiểm tra trên tất cả ${t.values.length} tổ hợp${dc.length?', bỏ qua các ô X':''}, và chỉ ra hàng sai nếu có.</p><label class="answer-label" for="answerType">Dạng đáp án</label><select class="answer-select" id="answerType"><option value="expr">Biểu thức Boole tương đương</option value="ones">Danh sách Σm (chỉ các hàng 1 đã xác định)</option><option value="zeros">Danh sách ΠM (chỉ các hàng 0 đã xác định)</option></select><label class="answer-label" for="answerInput">!A = phủ A · + = OR · * = AND · ^ = XOR</label><input id="answerInput" class="answer-input" autocomplete="off" spellcheck="false" placeholder="Ví dụ: !A*B + C" aria-describedby="feedback"><button class="check-button" id="checkAnswer">Kiểm tra đáp án →</button><button class="hint-button" id="hintBtn">Cho mình một gợi ý</button>`}<div id="feedback" aria-live="polite">${done.has(t.id)?'<p class="check-status">✓ Bạn đã hoàn thành mục này. Có thể luyện lại.</p><button class="hint-button" id="redoTask">Bỏ đánh dấu hoàn thành</button>':''}</div>`;
  }
}
function renderBelow(){
  const l=currentLesson(),t=currentTask();
  if(!l){$('#below').innerHTML=`<div class="result-summary"><div class="result-card"><h3><span>01</span> Tại sao nhóm lại giúp rút gọn?</h3><div class="formula">AB + A<span class="over">B</span> = A(B + <span class="over">B</span>) = A</div><p>B thay đổi nên được loại. A giữ nguyên nên ở lại. Mỗi lần tăng gấp đôi kích thước nhóm, ta khử thêm một biến.</p></div><div class="result-card"><h3><span>02</span> Bạn có thể học theo dạng</h3><p>Chọn bất kỳ bài ở thanh bên. Mỗi bài có 6 bước, được đi nhanh hoặc quay lại. Nút kiểm tra giúp bạn đánh dấu tiến độ.</p><p><b>Không khóa bài. Không cần học theo số thứ tự.</b></p></div></div><div class="callout"><b>↔</b><div>Mẹo nhớ: <b>SOP gom 1</b> để lấy tổng các tích. <b>POS gom 0</b> để lấy tích các tổng. Chọn được nhóm rồi mới viết biến.</div></div>`;return;}
  $('#below').innerHTML=`<div class="result-summary"><div class="result-card"><h3>Dữ kiện & điều cần tránh</h3><p>${l.insight}</p>${t.origin?`<p>Nguồn hàm: bài ${t.origin}.</p>`:''}${t.partial?'<p><b>Giới hạn của đề:</b> các hàng chưa quan sát được đánh X. Kết quả là một cách hoàn thiện phù hợp với giản đồ.</p>':''}<p class="dim">${t.vars.join('')} · ${t.values.length} tổ hợp · ${listIndices(t,'X').length} ô X</p></div><div class="result-card"><h3>Lời giải để đối chiếu · ${esc(t.name)}</h3>${S.step>=4?solutionHTML(t):'<p>Đến bước 5 để mở lời giải đầy đủ, hoặc bấm bên dưới nếu muốn đối chiếu ngay.</p><button class="hint-button" id="revealSolution">Xem lời giải của mục này</button>'}</div></div>${l.id.includes('-I')?'<div class="callout"><b>i</b><div>PDF đánh lặp số 2-14 đến 2-17. <b>I</b> = xuất hiện lần đầu; <b>II</b> = xuất hiện lần thứ hai. App giữ nguyên thứ tự và đủ tất cả bài.</div></div>':''}`;
}
function solutionHTML(t){return `${t.proof?'<div class="formula">'+format(t.expr)+' = '+format(t.right)+'</div>':''}<div class="monosmall">${esc(t.name)} = ${indexText(t)}<br>${esc(t.name)} = ${indexText(t,true)}</div><p class="formula">SOP gọn: ${format(t.sop.expr)}<br>POS gọn: ${format(t.pos.expr)}</p><details><summary>Khai triển dạng chuẩn 1 & 2</summary><p class="formula">Chuẩn 1: ${format(Engine.canonical(t.values,t.vars))}</p><p class="formula">Chuẩn 2: ${format(Engine.canonical(t.values,t.vars,true))}</p>${listIndices(t,'X').length?'<p>Hai biểu thức chuẩn trên xác định cùng các hàng bắt buộc; chúng có thể khác ở tập d. Luôn ghi kèm d('+listIndices(t,'X').join(',')+').</p>':''}</details>`;}
function introTask(){return S.step===4?setTask('F','A B C D',[1,3,7],[5]):S.step===5?setTask('F','A B C D',[0,1,4,5]):setTask('F','A B C D',[0,2,8,10]);}
function visualTask(){return currentTask()||introTask();}
function groupInfo(t,cells,pos){
  if(!cells.length)return null;const b=cells.map(i=>Engine.bits(i,t.vars.length)),pattern=t.vars.map((_,k)=>b.every(x=>x[k]===b[0][k])?String(b[0][k]):'-').join('');
  const full=Array.from({length:t.values.length},(_,i)=>i).filter(i=>Engine.bits(i,t.vars.length).every((bit,k)=>pattern[k]==='-'||+pattern[k]===bit));
  if(full.length!==cells.length)return {valid:false,message:'Nhóm chưa tạo thành một khối đầy đủ. Chọn hình chữ nhật 1, 2, 4, 8,… ô; được nối qua mép.'};
  if(cells.some(i=>t.values[i]===(pos?1:0)))return {valid:false,message:'Nhóm chứa ô '+(pos?'1':'0')+'. '+(pos?'POS chỉ gom ô 0 và X.':'SOP chỉ gom ô 1 và X.')};
  if(!cells.some(i=>t.values[i]===(pos?0:1)))return {valid:false,message:'Nhóm toàn X chưa phủ thêm ô bắt buộc nào. Hãy thêm ít nhất một ô '+(pos?'0':'1')+'.'};
  const kept=pattern.split('').flatMap((v,i)=>v==='-'?[]:[(pos?v==='1':v==='0')?'!'+t.vars[i]:t.vars[i]]);
  return {valid:true,pattern,term:kept.join(pos?'+':'*')||(pos?'0':'1'),removed:t.vars.filter((_,i)=>pattern[i]==='-'),count:cells.length};
}
function renderMap(t){
  const n=t.vars.length,layer=n===5?1:0,rowN=n===5?2:Math.floor(n/2),colN=n-layer-rowN;
  const gray=c=>Array.from({length:2**c},(_,i)=>i^(i>>1)),rows=gray(rowN),cols=gray(colN),groups=(S.pos?t.pos:t.sop)?.groups||Engine.minimize(t.values,t.vars,S.pos).groups;
  const maps=Array.from({length:2**layer},(_,part)=>`<div>${layer?`<p class="map-layer-label">${t.vars[0]} = ${part}</p>`:''}<div class="kmap ${n===3?'small':''}" style="grid-template-columns:38px repeat(${cols.length},minmax(42px,65px))"><div class="axis corner">${t.vars.slice(layer,layer+rowN).join('')}╲${t.vars.slice(layer+rowN).join('')}</div>${cols.map(c=>`<div class="axis">${Engine.bits(c,colN).join('')}</div>`).join('')}${rows.map(r=>`<div class="axis">${Engine.bits(r,rowN).join('')}</div>${cols.map(c=>{const i=part*2**(rowN+colN)+r*2**colN+c,v=t.values[i];return `<button class="map-cell ${v===1?'one':v==='X'?'dc':'zero'} ${S.selected.includes(i)?'selected':''}" data-cell="${i}" aria-pressed="${S.selected.includes(i)}" aria-label="m${i}, ${t.vars.join('')}=${Engine.bits(i,n).join('')}, F=${v}"><small>${i}</small>${v}</button>`;}).join('')}`).join('')}</div></div>`).join('');
  const gi=groupInfo(t,S.selected,S.pos);
  const message=gi?(gi.valid?`<strong>✓ Nhóm ${gi.count} ô → <span class="formula">${S.pos?'(':''}${format(gi.term)}${S.pos?')':''}</span></strong> · ${gi.removed.length?'Khử '+gi.removed.join(', ')+'.':'Chưa khử được biến.'}`:esc(gi.message)):'Bấm các ô để tạo một nhóm. App sẽ giải thích ngay bên dưới.';
  return `<div class="map-toolbar"><div class="segmented"><button data-pos="0" class="${!S.pos?'active':''}">SOP · gom 1</button><button data-pos="1" class="${S.pos?'active':''}">POS · gom 0</button></div><div><button class="board-button" id="sampleGroup">Nhóm mẫu ↗</button> <button class="board-button" id="clearGroup">Xóa chọn</button></div></div>${S.lesson<0?`<div class="hint-label">${['MỖI Ô LÀ MỘT TỔ HỢP ĐẦU VÀO','CHỈ MỘT BIT ĐỔI GIỮA HAI NHÃN KỀ NHAU','CÀNG NHIỀU Ô, CÀNG ÍT BIẾN','HAI MÉP NỐI VÒNG · BỐN GÓC LÀ MỘT NHÓM','DÙNG X ĐỂ NỚI NHÓM','CHỌN CÁC Ô 0, 1, 4, 5'][S.step]}</div>`:''}<div class="map-wrap">${maps}</div><div class="map-legend"><span><i class="legend-swatch"></i>F = 1</span><span><i class="legend-swatch zero"></i>F = 0</span><span><i class="legend-swatch dc"></i>${t.partial?'Chưa quan sát':'X tùy chọn'}</span></div>${gi?.valid?`<div class="variable-strip">${t.vars.map((v,i)=>`<span class="variable-token ${gi.pattern[i]==='-'?'removed':''}">${gi.pattern[i]==='-'?v:format((S.pos?gi.pattern[i]==='1':gi.pattern[i]==='0')?'!'+v:v)}</span>`).join('')}</div>`:''}<div class="group-message" aria-live="polite">${message}${S.selected.length===1?`<br>m${S.selected[0]} ↔ ${t.vars.join('')} = ${Engine.bits(S.selected[0],n).join('')}`:''}</div>${S.step>=3&&S.lesson>=0?`<div class="group-list">${groups.map((g,i)=>`<button data-group="${i}">${S.pos?'(':''}${format(g.term)}${S.pos?')':''} · ${g.cells.length} ô</button>`).join('')}</div>`:''}`;
}
function renderTruth(t){const transformed=t.proof?Engine.truth(t.proof[Math.min(Math.max(0,S.step-1),t.proof.length-1)][1],t.vars):null;return `<p class="board-sub">${t.vars.join('')} · i = ${t.vars.map((v,i)=>2**(t.vars.length-i-1)+v).join(' + ')} · bấm vào một hàng</p><div class="truth-scroll"><table class="truth-table"><thead><tr><th>i</th>${t.vars.map(v=>'<th>'+v+'</th>').join('')}<th>${esc(t.name)}</th>${transformed?'<th>Vế đổi</th><th>So sánh</th>':''}</tr></thead><tbody>${t.values.map((v,i)=>`<tr data-row="${i}" class="${i===S.frame?'active':''}"><td class="idx">${i}</td>${Engine.bits(i,t.vars.length).map(b=>'<td>'+b+'</td>').join('')}<td class="${v===1?'out-one':v==='X'?'out-dc':''}">${v}</td>${transformed?`<td>${transformed[i]}</td><td>${transformed[i]===v?'=':'≠'}</td>`:''}</tr>`).join('')}</tbody></table></div>`;}
function renderProof(t){const idx=Math.min(S.frame,t.proof.length-1),p=t.proof[idx];return `<div class="proof-stage"><div class="proof-label">BIẾN ĐỔI ${idx+1} / ${t.proof.length} · ${esc(p[0])}</div><div class="proof-current formula">${format(p[1])}</div>${idx>0?`<div class="proof-arrow">↑</div><div class="proof-before formula">${format(t.proof[idx-1][1])}</div>`:`<div class="proof-before">Mỗi bước giữ nguyên giá trị của hàm.</div>`}<div class="proof-law">${esc(p[2])}</div></div>`;}
function inputControls(t,i){return `<div class="input-bits">${t.vars.map((v,k)=>{const bit=Engine.bits(i,t.vars.length)[k];return `<label class="input-bit">${v}<button class="bit-button ${bit?'on':''}" data-bit="${k}" aria-label="Đổi ${v} từ ${bit} sang ${1-bit}">${bit}</button></label>`;}).join('')}</div>`;}
let circuitMode=null;
function circuitData(t){const mode=circuitMode||t.gate||'normal',expr=t.gate?(t.prefer==='pos'?t.pos.expr:t.sop.expr):t.expr||(t.prefer==='pos'?t.pos.expr:t.sop.expr),net=Engine.network(expr,t.vars,mode);return {mode,net,expr};}
function renderCircuit(t){
  const {mode,net}=circuitData(t),signals=Engine.simulate(net,Engine.env(S.frame,t.vars)),layers=[];
  net.nodes.forEach(n=>(layers[n.depth]??=[]).push(n));
  const width=Math.max(540,layers.length*122+45),height=Math.max(250,Math.max(...layers.map(l=>l.length))*73+75),pos=new Map();
  layers.forEach((list,d)=>list.forEach((n,k)=>pos.set(n.id,{x:40+d*122,y:65+(k+.5)*(height-85)/list.length})));
  let svg='';
  let longWire=0;
  for(const n of net.nodes){const p=pos.get(n.id);n.ins.forEach((id,k)=>{const q=pos.get(id),offset=(k-(n.ins.length-1)/2)*Math.min(10,28/n.ins.length),long=n.depth-net.nodes[id].depth>1,lane=14+(longWire++%7)*6;const route=long?`M${q.x+27} ${q.y} H${q.x+40} V${lane} H${p.x-47-k*3} V${p.y+offset} H${p.x-27}`:`M${q.x+27} ${q.y} H${p.x-47-k*3} V${p.y+offset} H${p.x-27}`;svg+=`<path class="wire ${signals[id]?'on':''}" d="${route}"/>`;});}
  for(const n of net.nodes){const p=pos.get(n.id),neg=['nand','nor','not'].includes(n.op),label=n.op==='var'||n.op==='const'?n.label:{and:'&',or:'≥1',xor:'=1',not:'1',nand:'&',nor:'≥1'}[n.op];svg+=`<g><title>${esc(n.op.toUpperCase())} ${n.ins.length} ngõ vào; giá trị ${signals[n.id]}</title><rect class="gate ${signals[n.id]?'on':''}" x="${p.x-27}" y="${p.y-19}" width="54" height="38" rx="${n.ins.length?5:16}"/><text text-anchor="middle" x="${p.x}" y="${p.y+4}">${label}</text>${neg?`<circle class="gate" cx="${p.x+29}" cy="${p.y}" r="3"/>`:''}<text text-anchor="middle" class="signal" x="${p.x}" y="${p.y+33}">${n.ins.length?'g'+n.id+' = ':''}${signals[n.id]}</text></g>`;}
  const p=pos.get(net.output);svg+=`<path class="wire ${signals[net.output]?'on':''}" d="M${p.x+33} ${p.y} h40"/><text x="${p.x+38}" y="${p.y-12}" class="signal">F=${signals[net.output]}</text>`;
  const signalName=id=>net.nodes[id].ins.length?'g'+id:net.nodes[id].label;
  return `<div class="map-toolbar"><span class="mini-stat">${net.nodes.filter(n=>n.ins.length).length} cổng · ${mode==='normal'?'logic cơ bản':mode.startsWith('nor')?'NOR · 2 ngõ':'NAND · 2 ngõ'}</span><div class="segmented"><button data-circuit-mode="normal" class="${mode==='normal'?'active':''}">Theo biểu thức</button><button data-circuit-mode="${t.gate||'nand2'}" class="${mode!=='normal'?'active':''}">${t.gate?.startsWith('nor')?'NOR':'NAND'}</button></div></div>${inputControls(t,S.frame)}<div class="circuit-scroll"><svg class="circuit-svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Sơ đồ mạch ${esc(t.name)}; đầu ra ${signals[net.output]}">${svg}</svg></div><p class="board-sub" style="margin:16px 0 0">Ký hiệu khối: & = AND; ≥1 = OR; =1 = XOR; vòng tròn = đảo. Kéo ngang để xem mạch dài.</p><details class="netlist"><summary>Xem cách nối từng cổng</summary>${net.nodes.filter(n=>n.ins.length).map(n=>`<div>g${n.id} = ${n.op.toUpperCase()}(${n.ins.map(signalName).join(', ')}) = ${signals[n.id]}</div>`).join('')}<div>F = ${signalName(net.output)} = ${signals[net.output]}</div></details>`;
}
function renderWave(t){
  const seq=t.wave||Array.from({length:t.values.length},(_,i)=>i),w=Math.max(640,seq.length*38+70),h=(t.vars.length+1)*62+43,dx=(w-84)/seq.length;
  const vals=t.vars.map((v,k)=>({label:v,values:seq.map(i=>Engine.bits(i,t.vars.length)[k])}));vals.push({label:t.name,values:seq.map(i=>t.values[i])});
  let svg=`<rect class="wave-cursor" x="${67+S.frame*dx}" y="8" width="${dx}" height="${h-20}" rx="3"/>`;
  for(let i=0;i<=seq.length;i++)svg+=`<line class="wave-grid" x1="${67+i*dx}" y1="8" x2="${67+i*dx}" y2="${h-20}"/>`;
  vals.forEach((row,k)=>{const base=46+k*62;svg+=`<text x="5" y="${base-9}">${esc(row.label)}</text>`;let path='';row.values.forEach((v,i)=>{const x=67+i*dx,y=base-(v===1?26:0);path+=(i?' L':'M')+x+' '+y+' H'+(x+dx);});svg+=`<path class="wave-path ${k===t.vars.length?'output':''}" d="${path}"/><text x="${70+S.frame*dx}" y="${base-34}" class="current">${row.values[S.frame]}</text>`;});
  seq.forEach((i,k)=>svg+=`<text x="${67+(k+.5)*dx}" y="${h-4}" text-anchor="middle" font-size="9">${i}</text>`);
  return `<p class="board-sub">Trục ngang: các khoảng ổn định · số dưới trục là chỉ số minterm i</p><div class="circuit-scroll"><svg class="wave-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Giản đồ xung ${esc(t.name)}"><title>Tín hiệu của đề và đầu ra F theo thời gian</title>${svg}</svg></div><div class="intro-question">Khoảng ${S.frame+1}: <strong>${t.vars.join('')} = ${Engine.bits(seq[S.frame],t.vars.length).join('')}</strong> → i = ${seq[S.frame]} → ${esc(t.name)} = <strong>${t.values[seq[S.frame]]}</strong></div>`;
}
function renderDecoder(t){const env=Engine.env(S.frame,t.vars),enabled=env.G1&&!env.G2,index=4*env.X2+2*env.X1+env.X0;return `${inputControls(t,S.frame)}<div class="intro-question">Cho phép: G1·!G2 = <strong>${+enabled}</strong> · X2X1X0 = <strong>${env.X2}${env.X1}${env.X0}</strong></div><div class="decoder-grid">${Array.from({length:8},(_,i)=>`<div class="decoder-output ${enabled&&i===index?'on':''}">Y${i}<b>${enabled&&i===index?1:0}</b></div>`).join('')}</div><p class="board-sub" style="text-align:center">${enabled?'Chỉ Y'+index+' sáng vì mã chọn bằng '+index+'.':'Đang cấm: tất cả ngõ ra đều bằng 0.'}</p><p class="board-sub" style="text-align:center">Tab Mạch vẽ các cổng của ${esc(t.name)}; chọn Y0–Y7 phía trên để xem đủ 8 nhánh.</p>`;}
function frameMax(){const t=currentTask();if(!t)return 2;if(S.view==='proof')return t.proof.length-1;if(S.view==='wave')return t.wave.length-1;if(S.view==='map')return Math.max(0,(S.pos?t.pos:t.sop).groups.length-1);return t.values.length-1;}
function renderVisual(){
  const t=visualTask();S.frame=Math.max(0,Math.min(S.frame,frameMax()));
  $('#visualTitle').textContent={map:'Bìa Karnaugh tương tác',truth:'Bảng chân trị',proof:'Biến đổi · từng bước một',circuit:'Mạch logic đang hoạt động',wave:'Giản đồ xung',decoder:'Giải mã 3 → 8'}[S.view];
  const el=$('#visualBody'),oldScroll=el.querySelector('.circuit-scroll'),scroll=oldScroll?{left:oldScroll.scrollLeft,top:oldScroll.scrollTop}:null;
  el.innerHTML=S.view==='map'?renderMap(t):S.view==='truth'?renderTruth(t):S.view==='proof'?renderProof(t):S.view==='circuit'?renderCircuit(t):S.view==='wave'?renderWave(t):renderDecoder(t);
  if(scroll&&el.querySelector('.circuit-scroll')){el.querySelector('.circuit-scroll').scrollLeft=scroll.left;el.querySelector('.circuit-scroll').scrollTop=scroll.top;}
  if(S.view==='truth'&&S.playing){const container=el.querySelector('.truth-scroll'),active=el.querySelector('tr.active');if(active)container.scrollTop=Math.max(0,active.offsetTop-container.offsetTop-container.clientHeight/2);}
  $('#scrubber').max=frameMax();$('#scrubber').value=S.frame;
  $('#frameLabel').textContent=S.view==='proof'?`${S.frame+1} / ${frameMax()+1}`:S.view==='wave'?`t ${S.frame+1}/${frameMax()+1}`:S.lesson<0?`mẫu ${S.frame+1}/3`:S.view==='map'?`nhóm ${S.frame+1}/${frameMax()+1}`:`i = ${S.frame}`;
  $('#visualCaption').textContent=S.view==='map'?'Nhấp để chọn/bỏ ô · Nhóm mẫu để xem một cách gom · SOP/POS đổi kiểu nhóm':S.view==='proof'?'▶ chạy các phép biến đổi · kéo thanh để dừng tại bước muốn xem':S.view==='circuit'?'Đường sáng = mức 1 · bấm đầu vào để thử · sơ đồ không mô phỏng trễ cổng':S.view==='wave'?'▶ chạy con trỏ theo thời gian · các khoảng tương ứng đúng giản đồ trong PDF':'▶ chạy từng tổ hợp · kéo thanh để chọn tổ hợp bất kỳ';
}
function applyFrame(){
  if(S.view==='map'){
    if(S.lesson<0){const sets=S.step===4?[[1],[1,3],[1,3,5,7]]:S.step===5?[[0],[0,1],[0,1,4,5]]:[[0],[0,2],[0,2,8,10]];S.selected=sets[S.frame]||sets[2];}
    else{const t=currentTask(),groups=(S.pos?t.pos:t.sop).groups;S.selected=groups[S.frame]?[...groups[S.frame].cells]:[];S.group=S.frame;}
  }
  renderVisual();
}
let timer;
function tick(){if(!S.playing)return;timer=setTimeout(()=>{if(!S.playing)return;if(S.frame>=frameMax()){stop();return;}S.frame++;applyFrame();tick();},(S.view==='proof'?2600:1350)/S.speed);}
function togglePlay(){if(S.playing){stop();return;}if(S.frame>=frameMax())S.frame=0;S.playing=true;$('#playBtn').textContent='Ⅱ';$('#playBtn').setAttribute('aria-label','Tạm dừng animation');applyFrame();tick();}
function feedback(text,success=false){const el=$('#feedback');if(el)el.innerHTML=`<div class="feedback ${success?'success':'error'}">${text}</div>`;}
function markDone(){const t=currentTask();if(!t)return;done.add(t.id);save();renderNav();document.querySelectorAll('[data-task]').forEach(b=>{const x=currentLesson().tasks[+b.dataset.task];b.classList.toggle('done',done.has(x.id));});toast('✓ Đã lưu: '+currentLesson().id+' · '+t.name);}
function checkAnswer(){
  const t=currentTask(),value=$('#answerInput').value.trim(),type=$('#answerType').value;
  if(type==='expr'){
    if(!value){feedback('Nhập một biểu thức trước nhé. Dùng !A hoặc A\' để phủ định A.');return;}
    try{const bad=Engine.mismatch(value,t);if(bad!==-1){const user=Engine.truth(value,t.vars)[bad];feedback(`Chưa khớp tại <b>i=${bad}</b>: ${t.vars.map((v,k)=>v+'='+Engine.bits(bad,t.vars.length)[k]).join(', ')}. Đề cần <b>${t.values[bad]}</b>, biểu thức bạn cho <b>${user}</b>.`);return;}feedback('✓ Đúng! Hai hàm trùng nhau trên tất cả các hàng xác định. Bạn có thể đối chiếu độ gọn và kiểu mạch với bước 5.',true);markDone();}catch(err){feedback(esc(err.message));}
  }else{
    if(value&&!/^\d+(?:[\s,;]+\d+)*$/.test(value)){feedback('Chỉ nhập các chỉ số, cách nhau bằng dấu phẩy. Nếu tập rỗng, để trống.');return;}
    const nums=value?value.split(/[\s,;]+/).map(Number):[],expected=listIndices(t,type==='ones'?1:0);
    if(new Set(nums).size!==nums.length){feedback('Có chỉ số bị lặp. Mỗi chỉ số chỉ cần ghi một lần.');return;}
    const extra=nums.filter(i=>!expected.includes(i)),missing=expected.filter(i=>!nums.includes(i));
    if(extra.length||missing.length){feedback((extra.length?'Chỉ số không thuộc tập này: <b>'+extra.join(', ')+'</b>. ':'')+(missing.length?'Còn thiếu <b>'+missing.length+'</b> hàng.':'')+' Ô X phải để trong tập d riêng.');return;}
    feedback('✓ Danh sách chính xác. '+(listIndices(t,'X').length?'Ghi kèm d('+listIndices(t,'X').join(',')+') trong đáp án.':''),true);markDone();
  }
}
function showHint(){const t=currentTask();S.hint++;const target=listIndices(t,1)[0]??listIndices(t,0)[0]??0;feedback(S.hint===1?`Thử i=${target}: ${t.vars.join('')}=${Engine.bits(target,t.vars.length).join('')}, F=${t.values[target]}. Khi viết SOP, bit 0 cần phủ định.`:S.hint===2?`Một kết quả gọn dùng ${t.sop.groups.length} nhóm 1. Nhóm đầu: {${t.sop.groups[0]?.cells.join(',')||'không có ô 1 bắt buộc'}}.`:`Đối chiếu một kết quả: <span class="formula">${format(t.sop.expr)}</span>. Thử tự giải thích vì sao nó đúng trước khi nhập.`,true);}
function nextItem(){if(S.lesson<0){selectLesson(7);return;}const l=currentLesson();if(S.task<l.tasks.length-1)selectLesson(S.lesson,S.task+1);else if(S.lesson<LESSONS.length-1)selectLesson(S.lesson+1);else{toast('Bạn đã đến cuối chương. Có thể chọn dạng bài muốn ôn ở thanh bên.');}}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalContent').innerHTML=html;$('#modal').showModal();}
function showSource(page){const p=page||currentLesson()?.page||7;openModal('Đề gốc · Chương 2 / BTC2.pdf',`<div class="source-tabs">${[5,6,7,8,9].map(i=>`<button data-source-page="${i}" ${i===p?'class="badge-done"':''}>Trang ${i}</button>`).join('')}</div><p>Chỉ hiển thị trang 5–9, thuộc chương 2. Bài 2-10 nối trang 6–7; bài 2-18 nối trang 8–9. Có thể phóng to trang bằng Ctrl + dấu cộng.</p><img src="${SOURCE_IMAGES[p]}" alt="BTC2.pdf, trang ${p}, chương 2 Đại số Boole">`);}
document.addEventListener('click',event=>{
  const b=event.target.closest('button');if(!b)return;
  if(b.dataset.lesson!==undefined){selectLesson(+b.dataset.lesson);return;}
  if(b.dataset.category){S.expanded=S.expanded===b.dataset.category?'':b.dataset.category;renderNav();return;}
  if(b.dataset.task!==undefined){selectLesson(S.lesson,+b.dataset.task);return;}
  if(b.dataset.step!==undefined){setStep(+b.dataset.step);return;}
  if(b.dataset.view){stop();S.view=b.dataset.view;S.frame=0;render();return;}
  if(b.dataset.cell!==undefined){stop();const i=+b.dataset.cell;S.selected=S.selected.includes(i)?S.selected.filter(x=>x!==i):[...S.selected,i];renderVisual();return;}
  if(b.dataset.pos!==undefined){stop();S.pos=b.dataset.pos==='1';S.selected=[];S.frame=0;S.group=-1;renderVisual();if(S.lesson>=0&&S.step===3)renderCoach();return;}
  if(b.dataset.group!==undefined){stop();S.frame=+b.dataset.group;applyFrame();return;}
  if(b.dataset.bit!==undefined){stop();S.frame^=2**(currentTask().vars.length-1-(+b.dataset.bit));renderVisual();return;}
  if(b.dataset.circuitMode){circuitMode=b.dataset.circuitMode;renderVisual();return;}
  if(b.dataset.introAnswer!==undefined){const ok=+b.dataset.introAnswer===0;b.classList.add(ok?'correct':'wrong');feedback(ok?'✓ Chính xác: A=0,C=0 giữ nguyên; B,D đổi nên mất. F=!A!C. Bạn đã sẵn sàng thử các bài 2-8, 2-13, 2-14.':'Chưa đúng. Hãy nhìn những bit giữ nguyên: A=0 và C=0.',ok);if(ok){saved.introDone=true;save();renderNav();}return;}
  if(b.dataset.proofAnswer!==undefined){const ok=+b.dataset.proofAnswer===currentTask().correct;b.classList.add(ok?'correct':'wrong');feedback(ok?'✓ Đúng quy tắc. Xem lại chuỗi biến đổi nếu muốn củng cố cách chứng minh.':'Chưa đúng. Quay lại bước biến đổi và nhìn hạng đang bị khử hoặc gộp.',ok);if(ok)markDone();return;}
  if(b.dataset.sourcePage){const p=+b.dataset.sourcePage;$('#modal').close();showSource(p);return;}
  switch(b.id){
    case'nextBtn':S.step<5?setStep(S.step+1):nextItem();break;
    case'prevBtn':setStep(S.step-1);break;
    case'skip1':setStep(S.step+2);break;
    case'skip2':setStep(S.step+3);break;
    case'playBtn':togglePlay();break;
    case'resetAnim':stop();S.frame=0;applyFrame();break;
    case'speedBtn':S.speed=S.speed===1?2:S.speed===2?.5:1;b.textContent=S.speed+'×';break;
    case'sampleGroup':stop();if(S.lesson<0){S.frame=2;applyFrame();}else{const groups=(S.pos?currentTask().pos:currentTask().sop).groups;if(!groups.length){toast('Không có ô bắt buộc cần gom ở chế độ này. Hàm có thể là hằng.');break;}S.group=(S.group+1)%groups.length;S.frame=S.group;applyFrame();}break;
    case'clearGroup':stop();S.selected=[];renderVisual();break;
    case'checkAnswer':checkAnswer();break;
    case'redoTask':done.delete(currentTask().id);save();render();toast('Đã bỏ đánh dấu để bạn luyện lại.');break;
    case'hintBtn':showHint();break;
    case'revealSolution':b.parentElement.innerHTML='<h3>Lời giải để đối chiếu</h3>'+solutionHTML(currentTask());break;
    case'sourceBtn':showSource();break;
    case'closeModal':$('#modal').close();break;
    case'menuBtn':document.body.classList.toggle('menu-open');break;
    case'helpBtn':openModal('Ký hiệu & cách học',`<p><b>Chọn tự do:</b> thanh bên chia 22 bài thành 6 dạng. Số I / II phân biệt các bài bị đánh số lặp trong PDF. Mỗi hàm có hướng dẫn riêng, tổng cộng ${TOTAL} mục.</p><p><b>Đi nhanh:</b> bấm bước bất kỳ, hoặc “Nhanh +1 bước” để bỏ qua 1 bước trung gian, “+2 bước” để bỏ qua 2 bước trung gian. Không bị khóa bài.</p><p><b>Nhập công thức:</b> !A hay A' = NOT; AB hoặc A*B = AND; A+B = OR; A^B = XOR. Thứ tự ưu tiên: NOT → AND → XOR → OR. Dùng ngoặc nếu trộn XOR với OR. !(A+B) phủ cả ngoặc. Chấp nhận dấu !, ~, ¬, ·, &, ⊕.</p><p><b>Dạng chuẩn 1:</b> tổng các minterm (SOP). <b>Dạng chuẩn 2:</b> tích các maxterm (POS). Σm liệt kê hàng 1, ΠM liệt kê hàng 0, d liệt kê các đầu ra tùy chọn.</p><p><b>Thứ tự biến:</b> dùng đúng thứ tự hiển thị. Riêng bài 2-2 là C,B,A. Bit bên trái là bit có trọng số lớn nhất.</p><p><b>Tiến độ:</b> trả lời đúng ở bước Tự kiểm tra để đánh dấu hoàn thành. Tự lưu vào trình duyệt đang dùng; chuyển trình duyệt hay xóa dữ liệu sẽ không giữ được tiến độ.</p><p><b>Phạm vi:</b> chỉ chương 2, trang 5–9 của BTC2.pdf. Phần hướng dẫn do app triển khai từ đề; hình đề gốc được nhúng để đối chiếu. Đồ thị biểu diễn logic lý tưởng, không thêm độ trễ không có trong đề.</p>`);break;
  }
});
document.addEventListener('click',event=>{const row=event.target.closest('[data-row]');if(row){stop();S.frame=+row.dataset.row;renderVisual();}if(document.body.classList.contains('menu-open')&&!event.composedPath().some(n=>n.id==='sidebar'||n.id==='menuBtn'))document.body.classList.remove('menu-open');});
$('#scrubber').addEventListener('input',e=>{stop();S.frame=+e.target.value;applyFrame();});
document.addEventListener('change',e=>{if(e.target.id==='answerType')$('#answerInput').placeholder=e.target.value==='expr'?'Ví dụ: !A*B + C':'Ví dụ: 0, 2, 5 (tập rỗng: để trống)';});
document.addEventListener('keydown',e=>{if(e.target.id==='answerInput'&&e.key==='Enter'){checkAnswer();return;}if(e.target.closest('input,select,textarea')||$('#modal').open)return;if(e.key==='ArrowRight'){e.preventDefault();setStep(S.step+1);}if(e.key==='ArrowLeft'){e.preventDefault();setStep(S.step-1);}});
$('.brand').addEventListener('click',e=>{e.preventDefault();selectLesson(-1);});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
S.view=chooseView();S.pos=currentTask()?.prefer==='pos';render();
